version: '3.8'
services:
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: records
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    build:
      context: ./pern/server
    image: pern-backend-image:latest
    restart: always
    ports:
      - "5050:5050"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/records
      DATABASE_HOST: db
      DATABASE_NAME: records
      DATABASE_USER: user
      DATABASE_PASSWORD: password
    depends_on:
      - db
  frontend:
    build:
      context: ./pern/client
    image: pern-frontend-image:latest
    ports:
      - "80:80"
    depends_on:
      - backend
volumes:
  postgres-data:
    driver: local
