apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: "{{ .Values.backend.image.pullPolicy }}"
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            - name: DATABASE_URL
              value: "{{ .Values.backend.env.DATABASE_URL }}"
            - name: DATABASE_HOST
              value: "{{ .Values.backend.env.DATABASE_HOST }}"
            - name: DATABASE_NAME
              value: "{{ .Values.backend.env.DATABASE_NAME }}"
            - name: DATABASE_USER
              value: "{{ .Values.backend.env.DATABASE_USER }}"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pern-application-postgresql
                  key: postgres-password

